language: java
addons:
    apt:
        packages:
            - libjhdf5-java
before_install:
    - jdk_switcher use oraclejdk8
    - export LD_LIBRARY_PATH=/usr/lib/jni/
    - export MAVEN_OPTS="-Djava.library.path=/usr/lib/jni/"
jdk:
    - oraclejdk8
