language: java
addons:
    apt:
        packages:
            - libgdal-dev
            - libgdal-java
            - build-essential
before_install:
    - jdk_switcher use oraclejdk8
    - find $HOME/.local/lib/
    - ./scripts/install_gdal.sh
jdk:
    - oraclejdk8
