#!/bin/sh

cat<<EOF > /etc/nginx/nginx.conf
worker_processes 4;

events {
    worker_connections 768;
}

http {
    server {
        location /entities {
            proxy_pass http://localhost:5000;
        }
        location / {
            proxy_pass http://localhost:3030;
        }
    }
}
EOF

case $@ in
start)
    set -e
    sudo systemctl start nginx
    nohup fuseki/run-fuseki.sh   > .fuseki.log  2>&1 & echo $! > .fuseki.pid
    nohup ./notelda.py runserver > .notelda.log 2>&1 & echo $! > .notelda.pid
    ;;
stop)
    sudo systemctl stop nginx
    kill $(cat .fuseki.pid)
    kill $(cat .notelda.pid)
    ;;
*)
    echo "Usage: $0 {start|stop}"
    ;;
esac;
