#!/bin/sh
case $1 in
start)
    set -e
    sudo systemctl start nginx
    nohup fuseki/run-fuseki.sh   > .fuseki.log  2>&1 & echo $! > .fuseki.pid
    ;;
stop)
    sudo systemctl stop nginx
    kill $(cat .fuseki.pid)  && rm .fuseki.pid
    ;;
configure)
    set -e
    site_name=fuseki-landsat
    sudo cp -v "nginx/$site_name" /etc/ninx/sites-available
    sudo ln -sv "/etc/nginx/sites-available/$site_name" "/etc/nginx/sites-enabled/$site_name"
    ;;
restart)
    $0 stop && $0 start
    ;;
*)
    echo "Usage: $0 {start|stop|configure}"
    ;;
esac;
